config/routes.rb
Rails.application.routes.draw do

  root to: 'admins#new', organization_id: 3
  
  get '/stops/download_template'

  delete '/logout',  to: 'sessions#destroy'

  resources :sessions
  resources :organizations, except: [:create, :destroy] do
    resources :admins
    resources :tours do
      resources :stops do
        collection do
          post :import
          delete :destroy_stops
        end
      end
    end
  end
end

app/views/admins/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admins/new.html.erb
<div class="logged_out">
  <div class="login_registration">
    <%= form_for [:organization, @admin] do |f| %>
    <% if @admin.errors.any? %>
    <div class="error_messages">
      <% @admin.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    </div>
    <% end %>
    <div class="field">
      <%= f.label :username %><br/>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </div>
    <div class="submit-button"><%= f.submit "REGISTER" %></div>
    <% end %>
  </div>
  <div class="italics">
    If you are already a registered user, go to the
    <%= link_to "Log In Page", new_session_path, {:class => "top_link"} %>.
  </div>
</div>

app/views/admins/show.html.erb
<h1>Admin#show</h1>
<p>Find me in app/views/admin/show.html.erb</p>

app/views/admins/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>