config/routes.rb
Rails.application.routes.draw do

  root to: 'admins#new', organization_id: 3
  
  get '/stops/download_template'

  delete '/logout',  to: 'sessions#destroy'

  resources :sessions
  resources :organizations, except: [:create, :destroy] do
    resources :admins
    resources :tours do
      resources :stops do
        collection do
          post :import
          delete :destroy_stops
        end
      end
    end
  end
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :tour
  belongs_to :admin

  validates_presence_of :stop_num
  validates_uniqueness_of :stop_num, scope: [:tour_id]

  validates_presence_of :name
  validates_presence_of :location

  require 'csv'

  def self.import(file, tour_id)
    tour = Tour.find_by(id: tour_id)
    if tour
      CSV.foreach(file.path, headers: true) do |row|
        tour.stops.create! row.to_hash
      end
    end
  end

  def self.to_csv(options = {})
    all_columns = column_names
    desired_columns = all_columns - ["id", "created_at", "updated_at"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |stop|
        csv << stop.attributes.values_at(*desired_columns)
      end
    end
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :update, :edit, :destroy]
  before_action :get_tour, except: [:download_template]

  def new
    if logged_in?
      if permitted_tour? && organization_member?
        @stop = Stop.new
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def index
    if logged_in?
      if permitted_tour? && organization_member?
        @stops = Stop.all
        respond_to do |format|
          format.html
          format.csv { send_data @tour.stops.to_csv }
          format.xls { send_data @tour.stops.to_csv(col_sep: "\t") }
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def show
    if logged_in?
      if permitted_tour? && organization_member?
        render :action => 'show.html' and return
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization." and return
      end
    end
    render :action => 'show.json'
  end

  def create
    if logged_in?
      if permitted_tour? && organization_member?
        @stop = @tour.stops.build(stop_params)
        @stop.admin = current_admin
        if @stop.save
          render 'show'
        else
          render 'new'
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def import
    if logged_in?
      if permitted_tour? && organization_member?
        Stop.import(params[:file], params[:tour_id])
        redirect_to organization_tour_stops_path, notice: "Data imported"
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def edit
    if logged_in?
      if permitted_tour? && organization_member?
        if current_admin == @stop.admin
          render :action => 'edit.html'
        else
          redirect_to organization_tour_stop_path(@current_admin.organization_id, @tour.id, @stop.stop_num), notice: "You are not authorized to edit this stop."
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view or edit content belonging to another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def download_template
    redirect_to new_session_path unless logged_in?
    send_file('./public/Tourify_stops_template.xlsx')
  end

  def update
    if logged_in?
      if permitted_tour? && organization_member?
        if current_admin == @stop.admin
          @stop.update!(stop_params)
          redirect_to organization_tour_stop_path
        else
          flash[:notice] = "You are not authorized to update this stop."
          render 'edit'
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def destroy
    if logged_in?
      if permitted_tour? && organization_member?
        if current_admin == @stop.admin
          @stop.destroy
          flash[:notice] = 'The stop was successfully deleted.'
          redirect_to organization_tour_stops_path
        else
          flash[:notice] = 'You are not authorized to delete this Stop.'
          render 'show'
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def destroy_stops
    @stops = @tour.stops
    if logged_in?
      if permitted_tour? && organization_member?
        if current_admin == @tour.admin
          @stops.destroy_all
          flash[:notice] = 'Stops were successfully deleted.'
          redirect_to organization_tour_stops_path
        else
          flash[:notice] = 'You are not authorized to delete these stops.'
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  private

  def stop_params
    params.require(:stop).permit(:stop_num, :name, :directions_to_next_stop, :learn_more_URL, :travel_tip, :description, :location, :image_current, :image_historic, :gps_long, :gps_lat, :badge)
  end

  def get_organization
    @organization = Organization.find(params[:organization_id])
  end

  def get_tour
    get_organization
    @tour = Tour.find(params[:tour_id])
  end

  def set_stop
    get_organization
    get_tour
    @stop = @tour.stops.find_by(stop_num: params[:id])
  end

  def organization_member?
    @organization = Organization.find(params[:organization_id])
    if @organization.id === @current_admin.organization_id
      return true
    end
  end

  def permitted_tour?
    @tour = Tour.find(params[:tour_id])
    allowed_org_id = @current_admin.organization_id
    allowed_tours = Tour.where organization_id: allowed_org_id
    allowed_tours.include? @tour
  end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/edit.html.erb
<div class="admin_form">

  <h1 class="stop_num"><%=@organization.name%>:
    <%= @tour.name%></h1>

  <div class="top_link_box">
    <div class="top_link">
      <%= link_to 'Back to Stops', organization_tour_stops_path(@organization, @tour) %>
    </div>
    <div class="top_link">
      <%= link_to "Back to Tour", organization_tour_path(@organization, @tour) %>
    </div>

    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@organization) %>
    </div>
  </div>

  <h2>Edit Stop
    <%= @stop.stop_num %>:
    <%= @stop.name %></h2>

  <%= form_for @stop, url: {action: "update"} do |f| %>

  <% if @stop.errors.any? %>
    <div class="error_messages">
      <ul>
        <% @stop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stop_num %><br/>
    <%= f.text_field :stop_num %>
  </div>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description, :rows => 12, :cols => 35 %>
  </div>

  <div class="field">
    <%= f.label :directions_to_next_stop %><br/>
    <%= f.text_field :directions_to_next_stop %>
  </div>

  <div class="field">
    <%= f.label :learn_more_URL %><br/>
    <%= f.text_field :learn_more_URL %>
  </div>

  <div class="field">
    <%= f.label :travel_tip %><br/>
    <%= f.text_field :travel_tip %>
  </div>

  <div class="field">
    <%= f.label :location %><br/>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :image_current %><br/>
    <%= f.text_field :image_current %>
  </div>

  <div class="field">
    <%= f.label :image_historic %><br/>
    <%= f.text_field :image_historic %>
  </div>

  <div class="field">
    <%= f.label :gps_long, "GPS longitude" %><br/>
    <%= f.text_field :gps_long %>
  </div>

  <div class="field">
    <%= f.label :gps_lat, "GPS latitude" %><br/>
    <%= f.text_field :gps_lat %>
  </div>

  <div class="field">
    <%= f.label :badge %><br/>
    <%= f.text_field :badge %>
  </div>

  <div class="submit">
    <div class="actions"><%= f.submit %></div>
  </div>

  <% end %>
</div>

app/views/stops/import.html.erb
<h1>Stops#import</h1>
<p>Find me in app/views/stops/import.html.erb</p>

app/views/stops/index.html.erb
<div class="hp">
  <br/>
  <h2>Stop list for the
    <%= @tour.name%></h2>

  <div class="top_link_box">
    <div class="top_link">
      <%= link_to "Back to Tour", organization_tour_path(@tour.organization_id, @tour.id) %>
    </div>

    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@tour.organization_id) %>
    </div>
  </div>

  <div>
    <h3 class="stop-h3">Bulk Upload Stop Data</h3>
    <p class="stop-para">To bulk upload stops for the
      <%= @tour.name%>
      tour you can import your content with a CSV File. If you have not done this before, you should
      <%= link_to 'download the template', stops_download_template_url %>.</p>

    <p>Once your stop data is in the template, use the buttons below to choose and import your CSV file:</p>

    <%= form_tag import_organization_tour_stops_path, multipart: true do %>
    <div class="import-csv">
      <div class="csv-options">
        <%= file_field_tag :file %>
      </div>
      <div class="import-button">
        <div class="submit">
          <%= submit_tag " Import CSV " %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <% if @tour.stops.blank? %>
  <% else %>
  <div class="show_when_stops">
    <h3 class="stop-h3">Bulk Edit Stop Data</h3>
    <p class="stop-para">Use the buttons below to download your existing stop data in either CSV or xls format. After editing the file, you can upload changes using the steps above.</p>
    <div class="outer_button_div">
      <div class="button_div">
        <div class="admin-btn"><%= link_to " CSV ", organization_tour_stops_path(format: "csv"), {:id => "button_left" } %>
        </div>
        <div class="admin-btn"><%= link_to "EXCEL", organization_tour_stops_path(format: "xls"), {:id => "button_right" } %>
        </div>
      </div>
    </div>

    <br/>
    <h3 class="stop-h3">Delete Stop Data</h3>
    <p class="stop-para">To delete stops individually, use the link next to each stop in the list below. To delete ALL stops at once, use the button below.</p>
    <div><%= button_to 'DELETE ALL STOPS', destroy_stops_organization_tour_stops_path(@organization.id), method: :delete, data: { confirm: 'This will delete ALL stops associated with this tour. Are you sure?' } %></div>
    <br/>

    <table>
      <thead>
        <tr>
          <th>Stop Number</th>
          <th>Stop Name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thread>
      <tbody>
        <% @tour.stops.sort_by { |stop| stop.stop_num }.each do |stop| %>
        <tr>
          <td><%= stop.stop_num %></td>
          <td><%= stop.name %></td>
          <td><%= link_to 'See stop details', organization_tour_stop_path(@organization.id, @tour.id, stop.stop_num) %></td>
          <td><%= link_to 'Edit stop details', edit_organization_tour_stop_path(@organization.id, @tour.id, stop.stop_num) %></td>
          <td><%= link_to 'Delete stop', organization_tour_stop_path(@organization.id, @tour.id, stop.stop_num), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

</div>
<br/>
<br/>

app/views/stops/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">stop_num</Data></Cell>
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="String">directions_to_next_stop</Data></Cell>
        <Cell><Data ss:Type="String">learn_more_URL</Data></Cell>
        <Cell><Data ss:Type="String">travel_tip</Data></Cell>
        <Cell><Data ss:Type="String">description</Data></Cell>
        <Cell><Data ss:Type="String">location</Data></Cell>
        <Cell><Data ss:Type="String">image_current</Data></Cell>
        <Cell><Data ss:Type="String">image_historic</Data></Cell>
        <Cell><Data ss:Type="String">gps_lat</Data></Cell>
        <Cell><Data ss:Type="String">gps_long</Data></Cell>
        <Cell><Data ss:Type="String">badge</Data></Cell>
        <Cell><Data ss:Type="String">tour_id</Data></Cell>
        <Cell><Data ss:Type="String">admin_id</Data></Cell>
      </Row>
    <% @stops.each do |stop| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= stop.stop_num %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.directions_to_next_stop %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.learn_more_URL %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.travel_tip %></Data></Cell>
        <Cell><Data ss:Type="Textarea"><%= stop.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.location %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.image_current %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.image_historic %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= stop.gps_lat %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= stop.gps_long %></Data></Cell>
        <Cell><Data ss:Type="String"><%= stop.badge %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= stop.tour_id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= stop.admin_id %></Data></Cell>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/stops/new.html.erb
<div class="admin_form">
  <h1 class="stop_num"><%=@organization.name%>:
    <%=@tour.name%></h1>

  <div class="top_link_box">
    <div class="top_link">
      <%= link_to 'Back to Stops', organization_tour_stops_path(@organization, @tour) %>
    </div>
    <div class="top_link">
      <%= link_to "Back to Tour", organization_tour_path(@organization, @tour) %>
    </div>

    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@organization) %>
    </div>
  </div>

  <h2>New Stop</h2>

  <% if @stop.errors.any? %>
    <div class="error_messages">
      <ul>
        <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @stop, url: {action: "create"}, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :stop_num %><br/>
    <%= f.text_field :stop_num %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :directions_to_next_stop %><br/>
    <%= f.text_field :directions_to_next_stop %>
  </div>

  <div class="field">
    <%= f.label :learn_more_URL %><br>
    <%= f.text_field :learn_more_URL %>
  </div>

  <div class="field">
    <%= f.label :travel_tip %><br/>
    <%= f.text_field :travel_tip %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :image_current %><br>
    <%= f.text_field :image_current %>
  </div>

  <div class="field">
    <%= f.label :image_historic %><br>
    <%= f.text_field :image_historic %>
  </div>

  <div class="field">
    <%= f.label :GPS_longitude, "GPS longitude" %><br>
    <%= f.text_field :gps_long %>
  </div>

  <div class="field">
    <%= f.label :gps_lat, "GPS latitude" %><br>
    <%= f.text_field :gps_lat %>
  </div>

  <div class="field">
    <%= f.label :badge %><br>
    <%= f.text_field :badge %>
  </div>

  <div class="submit">
    <div class="actions"><%= f.submit %></div>
  </div>
  <% end %>
</div>

app/views/stops/show.html.erb
<div class="hp">
  <h1 class="stop_num"><%=@organization.name%>: <%= @tour.name%></h1>

  <div class="top_link_box">
    <div class="top_link"><%= link_to 'Back to Stops', organization_tour_stops_path(@organization, @tour) %></div>
    <div class="top_link">
      <%= link_to "Back to Tour", organization_tour_path(@tour.organization_id, @tour.id) %>
    </div>

    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@tour.organization_id) %>
    </div>
  </div>

  <h2>STOP <%= @stop.stop_num %>: <%= @stop.name %></h2>
  <div class = "button_div">
    <div class="admin-btn"><%= link_to 'Edit Stop', edit_organization_tour_stop_path(@organization.id, @tour.id, @stop.stop_num), {:id => "button_left" } %>
    </div>

    <div class="admin-btn"><%= link_to 'Delete Stop', organization_tour_stop_path(@organization.id, @tour.id, @stop.stop_num), :id => "button_right", method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
  <br />


  <div class="stop_item">
    <p class="bold_text">Description:</p>
    <p class="stop_content"><%= @stop.description %></p>
  </div>

  <div class="stop_item">
    <p class="bold_text">Location:</p>
    <p class="stop_content"><%= @stop.location %></p>
  </div>

  <div class="stop_item">
    <p class="bold_text">Directions to next stop:</p>
    <p class="stop_content"><%= @stop.directions_to_next_stop %></p>
  </div>

  <div class="stop_item">
    <p class="bold_text">Travel tip:</p>
    <p class="stop_content"><%= @stop.travel_tip %></p>
  </div>

  <div class="coordinates_box">
    <div class="stop_item">
      <p class="bold_text">GPS longitude:</p><p class="stop_content"><%= @stop.gps_long %></p>
    </div>
    <div class="stop_item">
      <p class="bold_text">GPS latitude:</p><p class="stop_content"><%= @stop.gps_lat %></p>
    </div>
  </div>

  <div class="stop_item">
    <p class="bold_text">Learn_more_URL:</p>
    <p class="stop_content">
      <% if @stop.learn_more_URL != nil %>
        <%= link_to @stop.learn_more_URL, url_for(@stop.learn_more_URL) %>
      <% end %>
    </p>
  </div>

    <% if @stop.image_historic %>
      <div class="stop_item">
        <div class="images_holder">
          <p class="bold_text">Image Current:</p>
          <p class="stop_content">
            <% if @stop.image_current %>
              <%= image_tag(@stop.image_current, class: "style_image") %>
            <% end %>
          </p>
        </div>
      </div>
      <div class="stop_item">
          <p class="bold_text">Image Historic:</p>
          <p class="stop_content">
            <%= image_tag(@stop.image_historic, class: "style_image") %>
          </p>
      </div>

    <% else %>
      <div class="stop_item">
          <div class="images_holder">
            <p class="bold_text">Image Current:</p>
            <p class="stop_content"><%= image_tag(@stop.image_current, class: "style_image") %>
            </p>
          </div>
      </div>
      <div class="stop_item">
          <p class="bold_text">Image Historic:</p>
          <p class="stop_content">None available</p>
      </div>
    <% end %>

  <div class="link_container">
    <% if (@stop.stop_num-1 != 0) %>
      <div class="previous">
        <img src = "https://durhamdill.files.wordpress.com/2017/10/tourify-arrow.png" alt = "left arrow"/>
          <%= link_to "Previous Stop", organization_tour_stop_path(@stop.tour.organization_id, @stop.tour_id, @stop.stop_num-1) %>
      </div>
    <% end %>
      <div class="next">
        <%= link_to "Next Stop", organization_tour_stop_path(@stop.tour.organization_id, @stop.tour_id, @stop.stop_num+1) %>
        <img src = "https://durhamdill.files.wordpress.com/2017/10/tourify-arrow-right.png" alt = "right arrow"/>
      </div>
  </div>

  <br />

</div>