config/routes.rb
Rails.application.routes.draw do

  root to: 'admins#new', organization_id: 3
  
  get '/stops/download_template'

  delete '/logout',  to: 'sessions#destroy'

  resources :sessions
  resources :organizations, except: [:create, :destroy] do
    resources :admins
    resources :tours do
      resources :stops do
        collection do
          post :import
          delete :destroy_stops
        end
      end
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :admin
  belongs_to :organization

  has_many :stops, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :description
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :get_organization
  before_action :set_tour, except: [:index, :new, :create]

  def new
    if logged_in?
      if
        @tour = Tour.new
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to add content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def index
    if logged_in?
      if organization_member?
        redirect_to current_admin.organization
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to add content for another organization."
      end
    else
      flash[:alert] = 'Please login to continue.'
      redirect_to new_session_path
    end
  end

  def show
    if logged_in?
      if permitted_tour? && organization_member?
        render :action => 'show.html' and return
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization." and return
      end
    end
    render :action => 'show.json'
  end

  def create
    if logged_in?
      if organization_member?
        @tour = @organization.tours.build(tour_params)
        @tour.admin = current_admin
        if @tour.save
          redirect_to organization_path(@organization)
        else
          render 'new'
        end
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to create content for another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def edit
    if logged_in?
      if permitted_tour? && organization_member?
        render :action => 'edit.html'
      else
        redirect_to organization_tour_path(@current_admin.organization_id, @tour.id), notice: "You are not authorized to view or edit content belonging to another organization."
      end
    else
      redirect_to new_session_path
    end
  end

  def update
    if logged_in?
      if permitted_tour? && organization_member?
        @tour.update!(tour_params)
        if @tour.save
          render 'show'
        else
          render 'edit'
        end
      else
        redirect_to organization_tour_path(@current_admin.organization_id, @tour.id), notice: "You are not authorized to view or edit content belonging to another organization."
      end
    else
      flash[:notice] = 'You do not have authorization to edit this tour.'
      render 'show'
    end
  end

  def destroy
    if logged_in?
      if permitted_tour? && organization_member?
        @tour.destroy
        flash[:notice] = 'Tour was successfully deleted.'
        redirect_to @organization
      else
        redirect_to organization_tour_path(@current_admin.organization_id, @tour.id), notice: "You are not authorized to view or edit content belonging to another organization."
      end
    else
      flash[:notice] = 'You are not authorized to delete this Tour.'
      render 'show'
    end
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :description, :distance, :time_in_mins, :main_tour_photo)
  end

  def get_organization
    @organization = Organization.find(params[:organization_id])
  end

  def set_tour
    get_organization
    @tour = Tour.find(params[:id])
  end

  def organization_member?
    @organization = Organization.find(params[:organization_id])
    if @organization.id === @current_admin.organization_id
      return true
    end
  end

  def permitted_tour?
    @tour = Tour.find(params[:id])
    allowed_org_id = @current_admin.organization_id
    allowed_tours = Tour.where organization_id: allowed_org_id
    allowed_tours.include? @tour
  end
end

app/helpers/tour_helper.rb
module TourHelper
end

app/views/tours/create.html.erb
<h1>Tour#create</h1>
<p>Find me in app/views/tour/create.html.erb</p>

app/views/tours/edit.html.erb
<div class="admin_form">
  <h1 class="stop_num"><%=@organization.name%>: <%= @tour.name%></h1>
  <div class="top_link_box">
    <div class="top_link">
      <%= link_to "Back to Tour", organization_tour_path(@tour.organization_id, @tour.id) %>
    </div>
    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@tour.organization_id) %>
    </div>
  </div>

  <h2>Edit Tour</h2>

  <%= form_for [@organization, @tour] do |f| %>

  <% if @tour.errors.any? %>
    <div class="error_messages">
      <ul>
      <% @tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, :rows => 12, :cols => 35 %>
    </div>

    <div class="field">
      <%= f.label :main_tour_photo %><br />
      <%= f.text_field :main_tour_photo %>
    </div>

    <div class="field">
      <%= f.label :distance %><br />
      <%= f.text_field :distance %>
    </div>

    <div class="field">
      <%= f.label :time_in_mins %><br />
      <%= f.text_field :time_in_mins %>
    </div>

    <div class="submit">
      <div class="actions"><%= f.submit %></div>
    </div>

    <% end %>
</div>

app/views/tours/new.html.erb
<div class="admin_form">
  <h1 class="stop_num"><%=@organization.name%></h1>
  <div class="top_link_box">
    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@organization.id) %>
    </div>
  </div>

  <h2>Create a New Tour</h2>

  <% if @tour.errors.any? %>
    <div class="error_messages">
      <ul>
        <% @tour.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @tour, url: {action: "create"} do |form| %>

    <p>
      <%= form.label :name %><br />
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.label :main_tour_photo %><br>
      <%= form.text_field :main_tour_photo %>
    </p>

    <p>
      <%= form.label :distance %><br>
      <%= form.text_field :distance %>
    </p>

    <p>
      <%= form.label :time_in_mins %><br>
      <%= form.text_field :time_in_mins %>
    </p>


    <div class="submit">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/tours/show.html.erb
<div class="hp">

  <h1><%=@organization.name%>:
    <%= @tour.name%></h1>

  <div class="top_link_box">
    <div class="top_link">
      <%= link_to "Back to Organization", organization_path(@tour.organization_id) %>
    </div>
  </div>

  <h2>Tour Overview</h2>

  <% if @tour.main_tour_photo %>
        <%= image_tag(@tour.main_tour_photo, class: "main_tour_photo") %>
  <% end %>

  <ul>
    <li>Tour Name:
      <%= @tour.name %></li>
    <li>Total number of stops:
      <%= @tour.stops.count %></li>
    <li>Description:
      <%= @tour.description %>.</li>
    <li>Distance:
      <%= @tour.distance %>
      miles</li>
    <li>Time:
      <%= @tour.time_in_mins %>
      minutes</li>
    <li>Created By:
      <%= @tour.admin.username %></li>
    <li id="list_link">
      <div class="top_link">
        <%= link_to 'Edit tour overview', edit_organization_tour_path(@organization.id, @tour.id) %>
      </div>
    </li>
  </ul>
  <p class="stop-para">
    Visit the Stops Main Page to modify stops in bulk, delete stops, and more.
  </p>

  <div class="stop-btn"><%= link_to 'Stops Main Page', organization_tour_stops_path(@organization, @tour) %></div>

  <% if @tour.stops.blank? %>
  <% else %>
  <h2>Tour Stop List</h2>

  <table>
    <thead>
      <tr>
        <th>Stop Number</th>
        <th>Name</th>
        <th>Details</th>
      </tr>
    </thread>
    <tbody>
      <% @tour.stops.sort_by { |stop| stop.stop_num }.each do |stop| %>
      <tr>
        <td><%= stop.stop_num %></td>
        <td><%= stop.name %></td>
        <td><%= link_to 'See Stop Details', organization_tour_stop_path(@organization, @tour, stop.stop_num) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <br />
    <div class="stop-btn"><%= link_to 'Add Single Stop', new_organization_tour_stop_path(@organization, @tour) %></div>

  <br/>

app/views/tours/update.html.erb
<h1>Tour#update</h1>
<p>Find me in app/views/tour/update.html.erb</p>