config/routes.rb
Rails.application.routes.draw do

  root to: 'admins#new', organization_id: 3
  
  get '/stops/download_template'

  delete '/logout',  to: 'sessions#destroy'

  resources :sessions
  resources :organizations, except: [:create, :destroy] do
    resources :admins
    resources :tours do
      resources :stops do
        collection do
          post :import
          delete :destroy_stops
        end
      end
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :admins, dependent: :destroy
  has_many :tours, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :display_name

  require 'csv'

  def self.to_csv(options = {})
    org_columns =  column_names
    tour_info = ["tour_count", "tour_names"]
    desired_columns = org_columns - ["created_at", "updated_at"] + tour_info
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |org|
        csv << [org.id, org.name, org.description, org.url, org.logo_url, org.display_name, org.org_photo, org.content_credit, org.tours.count, org.tours.pluck(:name).join(', ')]
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # before_action:

  def new
    @organization = Organization.new
  end

  def index
    set_organization
    redirect_to organization_path(@organization.id) unless tourify_owner?
    @organizations = Organization.all
    respond_to do |format|
      format.html
      format.csv { send_data @organizations.to_csv }
      format.xls { send_data @organizations.to_csv(col_sep: "\t") }
    end
  end

  def show
    @organization = Organization.find(params[:id])
    if logged_in?
      if organization_member?
        render :action => 'show.html' and return
      else
        redirect_to organization_path(@current_admin.organization_id), notice: "You are not authorized to view, add, or edit content for another organization." and return
      end
    end
    render :action => 'show.json'
  end

  # def update
  #   @organization = Organization.find(params[:id])
  #   if logged_in? && current_admin.organization == @organization
  #     @organization.update!(organization_params)
  #     if @organization.save
  #       flash[:notice] = 'Organization information sucessfully updated'
  #       render :show
  #     else
  #       render :edit
  #     end
  #   elsif logged_in?
  #     redirect_to current_admin.organization
  #   else
  #     redirect_to new_session_path
  #   end
  # end
  #
  # def create
  #   @organization = Organization.create(organization_params)
  #   render :show, status: :created
  # end
  #
  # def destroy
  #   @organization = Organization.find(params[:id])
  #   if logged_in? && current_admin.organization == @organization
  #     @organization.destroy
  #     flash[:notice] = 'Organization successfully deleted.'
  #     redirect_to '/'
  #   else
  #     flash[:alert] = 'You are not authorized to delete this Organization.'
  #     render 'show'
  #   end
  # end

  private

  def organization_params
    params.require(:organization).permit(:name, :description, :url, :logo_url, :display_name, :org_photo)
  end

  def set_organization
    @organization = Organization.find_by(params[:id])
  end

  def organization_member?
    @organization = Organization.find(params[:id])
    if @organization.id === @current_admin.organization_id
      return true
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/index.html.erb
<div class="hp">

  <h2>Tourify registered members</h2>
  <br />
  <div class="top_link_box">
    <div class="top_link">
    </div>
  </div>

    <table id="org_table">
      <thead>
        <tr>
          <th>ID #</th>
          <th>Member Name</th>
          <th></th>
        </tr>
      </thread>
      <tbody>
        <% @organizations.each do |organization| %>
        <tr>
          <td><%= organization.id %></td>
          <td><div class="second_column">
            <%= organization.name %>
          </div></td>
          <td><%= link_to 'See details', organization_path(organization.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br />

    <div>
      <h3 class="stop-h3">Download information for Tourify registered members</h3>
      <p class="stop-para">Use the buttons below to download data for the organizations that have signed up for Tourify in either CSV or xls format.</p>
      <div class="outer_button_div">
        <div class="button_div">
          <div class="admin-btn"><%= link_to " CSV ", organizations_path(format: "csv"), {:id => "button_left" } %>
          </div>
          <div class="admin-btn"><%= link_to "EXCEL", organizations_path(format: "xls"), {:id => "button_right" } %>
          </div>
        </div>
      </div>
    </div>
    <br />
</div>

app/views/organizations/show.html.erb
<div class="hp">
  <br />
  <h1>Organization: <%=@organization.name%></h1>

  <% if @current_admin.organization_id != 2 %>
  <% else %>
  <div class="top_link_box">
    <div class="top_link">
      <%= link_to "Back to Organizations Index Page", organizations_path %>
    </div>
  </div>
  <% end %>

  <h3>Your organization currently has the following tours: </h3>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3">Links</th>
      </tr>
    </thead>
    <tbody>
      <% @organization.tours.each do |tour| %>
        <tr>
          <td><%=tour.name       %></td>
          <td><%=tour.description        %></td>
          <td><%= link_to 'See tour overview', organization_tour_path(@organization, tour.id) %></td>
          <td><%= link_to 'Edit tour overview', edit_organization_tour_path(@organization, tour.id) %></td>
          <td><%= link_to 'Delete tour', organization_tour_path(@organization, tour.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <button class = 'new-tour-btn'><%= link_to 'Create a new tour', new_organization_tour_path(@organization) %></button>


</div>